# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Unique assistant ID
assistant_id: 20250510-221545-nice-chord

# Language
language: en

# NLU Pipeline
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Core Policies
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
